name: Weekly Supabase Backup

on:
  schedule:
    - cron: '0 3 * * 0'   # Nedelja 03:00
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Call Supabase Weekly Backup
        run: |
          curl -X POST https://yunuwkjydqzgkqtbgwup.supabase.co/functions/v1/hyper-function \
  -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl1bnV3a2p5ZHF6Z2txdGJnd3VwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAyMzk1NjksImV4cCI6MjA4NTgxNTU2OX0.ogZt8LVk8i15_-eutFTVir9rX4Kt7iU5yeDs3WCH2uA
